### ISSUE TITLE
pull all keys up to a .env 

### ISSUE THREAD

**Issue by jb4earth** [novadaodev/homepage#21]
get all keys into a .env file - include dev mode toggle in here #20 

add .env to .gitignore

**Comment by dave-16** [comment]
all keys pulled to environments and not added to git ignore because right now our ioToad vercel account is down so if we add the environments to .gitignore now it might be little bit hard in testing so we can add to git ignore when we have our testing ioToad vercel account running  and after adding our keys in to vercel environment variables
